INSERT INTO states(is_active) VALUE(1);
INSERT INTO states(is_active) VALUE(0);

INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Bulbasaur', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Ivysaur', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Venusaur', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Charmander', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Charmeleon', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Charizard', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Squirtle', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Wartortle', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Blastoise', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Caterpie', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Metapod', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Butterfree', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Weedle', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Kakuna', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Beedrill', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Pidgey', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Pidgeotto', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Pidgeot', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Rattata', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Raticate', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Spearow', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Fearow', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Ekans', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Arbok', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Pikachu', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Raichu', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Sandshrew', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Sandslash', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Nidoran-W', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Nidorina', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Nidoqueen', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Nidoran-M', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Nidorino', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Nidoking', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Clefairy', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Clefable', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Vulpix', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Ninetales', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Jigglypuff', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Wigglytuff', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Zubat', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Golbat', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Oddish', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Gloom', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Vileplume', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Paras', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Parasect', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Venonat', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Venomoth', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Diglett', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Dugtrio', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Meowth', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Persian', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Psyduck', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Golduck', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Mankey', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Primeape', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Growlithe', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Arcanine', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Poliwag', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Poliwhirl', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Poliwrath', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Abra', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Kadabra', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Alakazam', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Machop', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Machoke', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Machamp', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Bellsprout', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Weepinbell', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Victreebel', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Tentacool', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Tentacruel', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Geodude', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Graveler', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Golem', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Ponyta', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Rapidash', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Slowpoke', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Slowbro', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Magnemite', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Magneton', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Farfetchd', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Doduo', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Dodrio', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Seel', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Dewgong', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Grimer', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Muk', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Shellder', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Cloyster', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Gastly', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Haunter', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Gengar', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Onix', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Drowzee', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Hypno', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Krabby', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Kingler', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Voltorb', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Electrode', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Exeggcute', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Exeggutor', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Cubone', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Marowak', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Hitmonlee', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Hitmonchan', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Lickitung', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Koffing', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Weezing', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Rhyhorn', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Rhydon', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Chansey', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Tangela', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Kangaskhan', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Horsea', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Seadra', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Goldeen', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Seaking', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Staryu', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Starmie', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Mr. Mime', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Scyther', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Jynx', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Electabuzz', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Magmar', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Pinsir', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Tauros', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Magikarp', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Gyarados', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Lapras', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Ditto', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Eevee', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Vaporeon', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Jolteon', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Flareon', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Porygon', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Omanyte', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Omastar', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Kabuto', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Kabutops', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Aerodactyl', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Snorlax', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Articuno', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Zapdos', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Moltres', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Dratini', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Dragonair', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Dragonite', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Mewtwo', 1);
INSERT INTO pokemons (pokemon_name, state_id) VALUES ('Mew', 1);

INSERT INTO types (type_name) VALUES ('Grass');
INSERT INTO types (type_name) VALUES ('Poison');
INSERT INTO types (type_name) VALUES ('Fire');
INSERT INTO types (type_name) VALUES ('Flying');
INSERT INTO types (type_name) VALUES ('Water');
INSERT INTO types (type_name) VALUES ('Bug');
INSERT INTO types (type_name) VALUES ('Normal');
INSERT INTO types (type_name) VALUES ('Electric');
INSERT INTO types (type_name) VALUES ('Ground');
INSERT INTO types (type_name) VALUES ('Fairy');
INSERT INTO types (type_name) VALUES ('Fighting');
INSERT INTO types (type_name) VALUES ('Psychic');
INSERT INTO types (type_name) VALUES ('Rock');
INSERT INTO types (type_name) VALUES ('Steel');
INSERT INTO types (type_name) VALUES ('Ice');
INSERT INTO types (type_name) VALUES ('Ghost');
INSERT INTO types (type_name) VALUES ('Dragon');

INSERT INTO pokemons_types VALUES (1,1);
INSERT INTO pokemons_types VALUES (1,2);
INSERT INTO pokemons_types VALUES (2,1);
INSERT INTO pokemons_types VALUES (2,2);
INSERT INTO pokemons_types VALUES (3,1);
INSERT INTO pokemons_types VALUES (3,2);
INSERT INTO pokemons_types VALUES (4,3);
INSERT INTO pokemons_types VALUES (5,3);
INSERT INTO pokemons_types VALUES (6,3);
INSERT INTO pokemons_types VALUES (6,4);
INSERT INTO pokemons_types VALUES (7,5);
INSERT INTO pokemons_types VALUES (8,5);
INSERT INTO pokemons_types VALUES (9,5);
INSERT INTO pokemons_types VALUES (10,6);
INSERT INTO pokemons_types VALUES (11,6);
INSERT INTO pokemons_types VALUES (12,6);
INSERT INTO pokemons_types VALUES (12,4);
INSERT INTO pokemons_types VALUES (13,6);
INSERT INTO pokemons_types VALUES (13,2);
INSERT INTO pokemons_types VALUES (14,6);
INSERT INTO pokemons_types VALUES (14,2);
INSERT INTO pokemons_types VALUES (15,6);
INSERT INTO pokemons_types VALUES (15,2);
INSERT INTO pokemons_types VALUES (16,7);
INSERT INTO pokemons_types VALUES (16,4);
INSERT INTO pokemons_types VALUES (17,7);
INSERT INTO pokemons_types VALUES (17,4);
INSERT INTO pokemons_types VALUES (18,7);
INSERT INTO pokemons_types VALUES (18,4);
INSERT INTO pokemons_types VALUES (19,7);
INSERT INTO pokemons_types VALUES (20,7);
INSERT INTO pokemons_types VALUES (21,7);
INSERT INTO pokemons_types VALUES (21,4);
INSERT INTO pokemons_types VALUES (22,7);
INSERT INTO pokemons_types VALUES (22,4);
INSERT INTO pokemons_types VALUES (23,2);
INSERT INTO pokemons_types VALUES (24,2);
INSERT INTO pokemons_types VALUES (25,8);
INSERT INTO pokemons_types VALUES (26,8);
INSERT INTO pokemons_types VALUES (27,9);
INSERT INTO pokemons_types VALUES (28,9);
INSERT INTO pokemons_types VALUES (29,2);
INSERT INTO pokemons_types VALUES (30,2);
INSERT INTO pokemons_types VALUES (31,2);
INSERT INTO pokemons_types VALUES (31,9);
INSERT INTO pokemons_types VALUES (32,2);
INSERT INTO pokemons_types VALUES (33,2);
INSERT INTO pokemons_types VALUES (34,2);
INSERT INTO pokemons_types VALUES (34,9);
INSERT INTO pokemons_types VALUES (35,10);
INSERT INTO pokemons_types VALUES (36,10);
INSERT INTO pokemons_types VALUES (37,3);
INSERT INTO pokemons_types VALUES (38,3);
INSERT INTO pokemons_types VALUES (39,7);
INSERT INTO pokemons_types VALUES (39,10);
INSERT INTO pokemons_types VALUES (40,7);
INSERT INTO pokemons_types VALUES (40,10);
INSERT INTO pokemons_types VALUES (41,2);
INSERT INTO pokemons_types VALUES (41,4);
INSERT INTO pokemons_types VALUES (42,2);
INSERT INTO pokemons_types VALUES (42,4);
INSERT INTO pokemons_types VALUES (43,1);
INSERT INTO pokemons_types VALUES (43,2);
INSERT INTO pokemons_types VALUES (44,1);
INSERT INTO pokemons_types VALUES (44,2);
INSERT INTO pokemons_types VALUES (45,1);
INSERT INTO pokemons_types VALUES (45,2);
INSERT INTO pokemons_types VALUES (46,6);
INSERT INTO pokemons_types VALUES (46,1);
INSERT INTO pokemons_types VALUES (47,6);
INSERT INTO pokemons_types VALUES (47,1);
INSERT INTO pokemons_types VALUES (48,6);
INSERT INTO pokemons_types VALUES (48,2);
INSERT INTO pokemons_types VALUES (49,6);
INSERT INTO pokemons_types VALUES (49,2);
INSERT INTO pokemons_types VALUES (50,9);
INSERT INTO pokemons_types VALUES (51,9);
INSERT INTO pokemons_types VALUES (52,7);
INSERT INTO pokemons_types VALUES (53,7);
INSERT INTO pokemons_types VALUES (54,5);
INSERT INTO pokemons_types VALUES (55,5);
INSERT INTO pokemons_types VALUES (56,11);
INSERT INTO pokemons_types VALUES (57,11);
INSERT INTO pokemons_types VALUES (58,3);
INSERT INTO pokemons_types VALUES (59,3);
INSERT INTO pokemons_types VALUES (60,5);
INSERT INTO pokemons_types VALUES (61,5);
INSERT INTO pokemons_types VALUES (62,5);
INSERT INTO pokemons_types VALUES (62,11);
INSERT INTO pokemons_types VALUES (63, 12);
INSERT INTO pokemons_types VALUES (64, 12);
INSERT INTO pokemons_types VALUES (65, 12);
INSERT INTO pokemons_types VALUES (66, 11);
INSERT INTO pokemons_types VALUES (67, 11);
INSERT INTO pokemons_types VALUES (68, 11);
INSERT INTO pokemons_types VALUES (69, 1);
INSERT INTO pokemons_types VALUES (69, 2);
INSERT INTO pokemons_types VALUES (70, 1);
INSERT INTO pokemons_types VALUES (70, 2);
INSERT INTO pokemons_types VALUES (71, 1);
INSERT INTO pokemons_types VALUES (71, 2);
INSERT INTO pokemons_types VALUES (72, 5);
INSERT INTO pokemons_types VALUES (72, 2);
INSERT INTO pokemons_types VALUES (73, 5);
INSERT INTO pokemons_types VALUES (73, 2);
INSERT INTO pokemons_types VALUES (74, 13);
INSERT INTO pokemons_types VALUES (74, 9);
INSERT INTO pokemons_types VALUES (75, 13);
INSERT INTO pokemons_types VALUES (75, 9);
INSERT INTO pokemons_types VALUES (76, 13);
INSERT INTO pokemons_types VALUES (76, 9);
INSERT INTO pokemons_types VALUES (77, 3);
INSERT INTO pokemons_types VALUES (78, 3);
INSERT INTO pokemons_types VALUES (79, 5);
INSERT INTO pokemons_types VALUES (79, 12);
INSERT INTO pokemons_types VALUES (80, 5);
INSERT INTO pokemons_types VALUES (80, 12);
INSERT INTO pokemons_types VALUES (81, 8);
INSERT INTO pokemons_types VALUES (81, 14);
INSERT INTO pokemons_types VALUES (82, 8);
INSERT INTO pokemons_types VALUES (82, 14);
INSERT INTO pokemons_types VALUES (83, 7);
INSERT INTO pokemons_types VALUES (83, 4);
INSERT INTO pokemons_types VALUES (84, 7);
INSERT INTO pokemons_types VALUES (84, 4);
INSERT INTO pokemons_types VALUES (85, 7);
INSERT INTO pokemons_types VALUES (85, 4);
INSERT INTO pokemons_types VALUES (86, 5);
INSERT INTO pokemons_types VALUES (87, 5);
INSERT INTO pokemons_types VALUES (87, 15);
INSERT INTO pokemons_types VALUES (88, 2);
INSERT INTO pokemons_types VALUES (89, 2);
INSERT INTO pokemons_types VALUES (90, 5);
INSERT INTO pokemons_types VALUES (91, 5);
INSERT INTO pokemons_types VALUES (91, 15);
INSERT INTO pokemons_types VALUES (92, 16);
INSERT INTO pokemons_types VALUES (92, 2);
INSERT INTO pokemons_types VALUES (93, 16);
INSERT INTO pokemons_types VALUES (93, 2);
INSERT INTO pokemons_types VALUES (94, 16);
INSERT INTO pokemons_types VALUES (94, 2);
INSERT INTO pokemons_types VALUES (95, 13);
INSERT INTO pokemons_types VALUES (95, 9);
INSERT INTO pokemons_types VALUES (96, 12);
INSERT INTO pokemons_types VALUES (97, 12);
INSERT INTO pokemons_types VALUES (98, 5);
INSERT INTO pokemons_types VALUES (99, 5);
INSERT INTO pokemons_types VALUES (100, 8);
INSERT INTO pokemons_types VALUES (101, 8);
INSERT INTO pokemons_types VALUES (102, 1);
INSERT INTO pokemons_types VALUES (102, 12);
INSERT INTO pokemons_types VALUES (103, 1);
INSERT INTO pokemons_types VALUES (103, 12);
INSERT INTO pokemons_types VALUES (104, 9);
INSERT INTO pokemons_types VALUES (105, 9);
INSERT INTO pokemons_types VALUES (106, 11);
INSERT INTO pokemons_types VALUES (107, 11);
INSERT INTO pokemons_types VALUES (108, 7);
INSERT INTO pokemons_types VALUES (109, 2);
INSERT INTO pokemons_types VALUES (110, 2);
INSERT INTO pokemons_types VALUES (111, 9);
INSERT INTO pokemons_types VALUES (111, 13);
INSERT INTO pokemons_types VALUES (112, 9);
INSERT INTO pokemons_types VALUES (112, 13);
INSERT INTO pokemons_types VALUES (113, 7);
INSERT INTO pokemons_types VALUES (114, 1);
INSERT INTO pokemons_types VALUES (115, 7);
INSERT INTO pokemons_types VALUES (116, 5);
INSERT INTO pokemons_types VALUES (117, 5);
INSERT INTO pokemons_types VALUES (118, 5);
INSERT INTO pokemons_types VALUES (119, 5);
INSERT INTO pokemons_types VALUES (120, 5);
INSERT INTO pokemons_types VALUES (121, 5);
INSERT INTO pokemons_types VALUES (121, 12);
INSERT INTO pokemons_types VALUES (122, 12);
INSERT INTO pokemons_types VALUES (122, 10);
INSERT INTO pokemons_types VALUES (123, 6);
INSERT INTO pokemons_types VALUES (123, 11);
INSERT INTO pokemons_types VALUES (124, 15);
INSERT INTO pokemons_types VALUES (124, 12);
INSERT INTO pokemons_types VALUES (125, 8);
INSERT INTO pokemons_types VALUES (126, 3);
INSERT INTO pokemons_types VALUES (127, 6);
INSERT INTO pokemons_types VALUES (128, 7);
INSERT INTO pokemons_types VALUES (129, 5);
INSERT INTO pokemons_types VALUES (130, 5);
INSERT INTO pokemons_types VALUES (130, 4);
INSERT INTO pokemons_types VALUES (131, 5);
INSERT INTO pokemons_types VALUES (131, 15);
INSERT INTO pokemons_types VALUES (132, 7);
INSERT INTO pokemons_types VALUES (133, 7);
INSERT INTO pokemons_types VALUES (134, 5);
INSERT INTO pokemons_types VALUES (135, 8);
INSERT INTO pokemons_types VALUES (136, 3);
INSERT INTO pokemons_types VALUES (137, 7);
INSERT INTO pokemons_types VALUES (138, 13);
INSERT INTO pokemons_types VALUES (138, 5);
INSERT INTO pokemons_types VALUES (139, 13);
INSERT INTO pokemons_types VALUES (139, 5);
INSERT INTO pokemons_types VALUES (140, 13);
INSERT INTO pokemons_types VALUES (140, 5);
INSERT INTO pokemons_types VALUES (141, 13);
INSERT INTO pokemons_types VALUES (141, 5);
INSERT INTO pokemons_types VALUES (142, 13);
INSERT INTO pokemons_types VALUES (142, 4);
INSERT INTO pokemons_types VALUES (143, 7);
INSERT INTO pokemons_types VALUES (144, 15);
INSERT INTO pokemons_types VALUES (144, 4);
INSERT INTO pokemons_types VALUES (145, 8);
INSERT INTO pokemons_types VALUES (145, 4);
INSERT INTO pokemons_types VALUES (146, 3);
INSERT INTO pokemons_types VALUES (146, 4);
INSERT INTO pokemons_types VALUES (147, 17);
INSERT INTO pokemons_types VALUES (148, 17);
INSERT INTO pokemons_types VALUES (149, 17);
INSERT INTO pokemons_types VALUES (149, 4);
INSERT INTO pokemons_types VALUES (150, 12);
INSERT INTO pokemons_types VALUES (151, 12);