INSERT INTO pokemons (pokemon_name) VALUE ('Bulbasaur');
INSERT INTO pokemons (pokemon_name) VALUE ('Ivysaur');
INSERT INTO pokemons (pokemon_name) VALUE ('Venusaur');
INSERT INTO pokemons (pokemon_name) VALUE ('Charmander');
INSERT INTO pokemons (pokemon_name) VALUE ('Charmeleon');
INSERT INTO pokemons (pokemon_name) VALUE ('Charizard');
INSERT INTO pokemons (pokemon_name) VALUE ('Squirtle');
INSERT INTO pokemons (pokemon_name) VALUE ('Wartortle');
INSERT INTO pokemons (pokemon_name) VALUE ('Blastoise');
INSERT INTO pokemons (pokemon_name) VALUE ('Caterpie');
INSERT INTO pokemons (pokemon_name) VALUE ('Metapod');
INSERT INTO pokemons (pokemon_name) VALUE ('Butterfree');
INSERT INTO pokemons (pokemon_name) VALUE ('Weedle');
INSERT INTO pokemons (pokemon_name) VALUE ('Kakuna');
INSERT INTO pokemons (pokemon_name) VALUE ('Beedrill');
INSERT INTO pokemons (pokemon_name) VALUE ('Pidgey');
INSERT INTO pokemons (pokemon_name) VALUE ('Pidgeotto');
INSERT INTO pokemons (pokemon_name) VALUE ('Pidgeot');
INSERT INTO pokemons (pokemon_name) VALUE ('Rattata');
INSERT INTO pokemons (pokemon_name) VALUE ('Raticate');
INSERT INTO pokemons (pokemon_name) VALUE ('Spearow');
INSERT INTO pokemons (pokemon_name) VALUE ('Fearow');
INSERT INTO pokemons (pokemon_name) VALUE ('Ekans');
INSERT INTO pokemons (pokemon_name) VALUE ('Arbok');
INSERT INTO pokemons (pokemon_name) VALUE ('Pikachu');
INSERT INTO pokemons (pokemon_name) VALUE ('Raichu');
INSERT INTO pokemons (pokemon_name) VALUE ('Sandshrew');
INSERT INTO pokemons (pokemon_name) VALUE ('Sandslash');
INSERT INTO pokemons (pokemon_name) VALUE ('Nidoran-W');
INSERT INTO pokemons (pokemon_name) VALUE ('Nidorina');
INSERT INTO pokemons (pokemon_name) VALUE ('Nidoqueen');
INSERT INTO pokemons (pokemon_name) VALUE ('Nidoran-M');
INSERT INTO pokemons (pokemon_name) VALUE ('Nidorino');
INSERT INTO pokemons (pokemon_name) VALUE ('Nidoking');
INSERT INTO pokemons (pokemon_name) VALUE ('Clefairy');
INSERT INTO pokemons (pokemon_name) VALUE ('Clefable');
INSERT INTO pokemons (pokemon_name) VALUE ('Vulpix');
INSERT INTO pokemons (pokemon_name) VALUE ('Ninetales');
INSERT INTO pokemons (pokemon_name) VALUE ('Jigglypuff');
INSERT INTO pokemons (pokemon_name) VALUE ('Wigglytuff');
INSERT INTO pokemons (pokemon_name) VALUE ('Zubat');
INSERT INTO pokemons (pokemon_name) VALUE ('Golbat');
INSERT INTO pokemons (pokemon_name) VALUE ('Oddish');
INSERT INTO pokemons (pokemon_name) VALUE ('Gloom');
INSERT INTO pokemons (pokemon_name) VALUE ('Vileplume');
INSERT INTO pokemons (pokemon_name) VALUE ('Paras');
INSERT INTO pokemons (pokemon_name) VALUE ('Parasect');
INSERT INTO pokemons (pokemon_name) VALUE ('Venonat');
INSERT INTO pokemons (pokemon_name) VALUE ('Venomoth');
INSERT INTO pokemons (pokemon_name) VALUE ('Diglett');
INSERT INTO pokemons (pokemon_name) VALUE ('Dugtrio');
INSERT INTO pokemons (pokemon_name) VALUE ('Meowth');
INSERT INTO pokemons (pokemon_name) VALUE ('Persian');
INSERT INTO pokemons (pokemon_name) VALUE ('Psyduck');
INSERT INTO pokemons (pokemon_name) VALUE ('Golduck');
INSERT INTO pokemons (pokemon_name) VALUE ('Mankey');
INSERT INTO pokemons (pokemon_name) VALUE ('Primeape');
INSERT INTO pokemons (pokemon_name) VALUE ('Growlithe');
INSERT INTO pokemons (pokemon_name) VALUE ('Arcanine');
INSERT INTO pokemons (pokemon_name) VALUE ('Poliwag');
INSERT INTO pokemons (pokemon_name) VALUE ('Poliwhirl');
INSERT INTO pokemons (pokemon_name) VALUE ('Poliwrath');
INSERT INTO pokemons (pokemon_name) VALUE ('Abra');
INSERT INTO pokemons (pokemon_name) VALUE ('Kadabra');
INSERT INTO pokemons (pokemon_name) VALUE ('Alakazam');
INSERT INTO pokemons (pokemon_name) VALUE ('Machop');
INSERT INTO pokemons (pokemon_name) VALUE ('Machoke');
INSERT INTO pokemons (pokemon_name) VALUE ('Machamp');
INSERT INTO pokemons (pokemon_name) VALUE ('Bellsprout');
INSERT INTO pokemons (pokemon_name) VALUE ('Weepinbell');
INSERT INTO pokemons (pokemon_name) VALUE ('Victreebel');
INSERT INTO pokemons (pokemon_name) VALUE ('Tentacool');
INSERT INTO pokemons (pokemon_name) VALUE ('Tentacruel');
INSERT INTO pokemons (pokemon_name) VALUE ('Geodude');
INSERT INTO pokemons (pokemon_name) VALUE ('Graveler');
INSERT INTO pokemons (pokemon_name) VALUE ('Golem');
INSERT INTO pokemons (pokemon_name) VALUE ('Ponyta');
INSERT INTO pokemons (pokemon_name) VALUE ('Rapidash');
INSERT INTO pokemons (pokemon_name) VALUE ('Slowpoke');
INSERT INTO pokemons (pokemon_name) VALUE ('Slowbro');
INSERT INTO pokemons (pokemon_name) VALUE ('Magnemite');
INSERT INTO pokemons (pokemon_name) VALUE ('Magneton');
INSERT INTO pokemons (pokemon_name) VALUE ('Farfetchd');
INSERT INTO pokemons (pokemon_name) VALUE ('Doduo');
INSERT INTO pokemons (pokemon_name) VALUE ('Dodrio');
INSERT INTO pokemons (pokemon_name) VALUE ('Seel');
INSERT INTO pokemons (pokemon_name) VALUE ('Dewgong');
INSERT INTO pokemons (pokemon_name) VALUE ('Grimer');
INSERT INTO pokemons (pokemon_name) VALUE ('Muk');
INSERT INTO pokemons (pokemon_name) VALUE ('Shellder');
INSERT INTO pokemons (pokemon_name) VALUE ('Cloyster');
INSERT INTO pokemons (pokemon_name) VALUE ('Gastly');
INSERT INTO pokemons (pokemon_name) VALUE ('Haunter');
INSERT INTO pokemons (pokemon_name) VALUE ('Gengar');
INSERT INTO pokemons (pokemon_name) VALUE ('Onix');
INSERT INTO pokemons (pokemon_name) VALUE ('Drowzee');
INSERT INTO pokemons (pokemon_name) VALUE ('Hypno');
INSERT INTO pokemons (pokemon_name) VALUE ('Krabby');
INSERT INTO pokemons (pokemon_name) VALUE ('Kingler');
INSERT INTO pokemons (pokemon_name) VALUE ('Voltorb');
INSERT INTO pokemons (pokemon_name) VALUE ('Electrode');
INSERT INTO pokemons (pokemon_name) VALUE ('Exeggcute');
INSERT INTO pokemons (pokemon_name) VALUE ('Exeggutor');
INSERT INTO pokemons (pokemon_name) VALUE ('Cubone');
INSERT INTO pokemons (pokemon_name) VALUE ('Marowak');
INSERT INTO pokemons (pokemon_name) VALUE ('Hitmonlee');
INSERT INTO pokemons (pokemon_name) VALUE ('Hitmonchan');
INSERT INTO pokemons (pokemon_name) VALUE ('Lickitung');
INSERT INTO pokemons (pokemon_name) VALUE ('Koffing');
INSERT INTO pokemons (pokemon_name) VALUE ('Weezing');
INSERT INTO pokemons (pokemon_name) VALUE ('Rhyhorn');
INSERT INTO pokemons (pokemon_name) VALUE ('Rhydon');
INSERT INTO pokemons (pokemon_name) VALUE ('Chansey');
INSERT INTO pokemons (pokemon_name) VALUE ('Tangela');
INSERT INTO pokemons (pokemon_name) VALUE ('Kangaskhan');
INSERT INTO pokemons (pokemon_name) VALUE ('Horsea');
INSERT INTO pokemons (pokemon_name) VALUE ('Seadra');
INSERT INTO pokemons (pokemon_name) VALUE ('Goldeen');
INSERT INTO pokemons (pokemon_name) VALUE ('Seaking');
INSERT INTO pokemons (pokemon_name) VALUE ('Staryu');
INSERT INTO pokemons (pokemon_name) VALUE ('Starmie');
INSERT INTO pokemons (pokemon_name) VALUE ('Mr. Mime');
INSERT INTO pokemons (pokemon_name) VALUE ('Scyther');
INSERT INTO pokemons (pokemon_name) VALUE ('Jynx');
INSERT INTO pokemons (pokemon_name) VALUE ('Electabuzz');
INSERT INTO pokemons (pokemon_name) VALUE ('Magmar');
INSERT INTO pokemons (pokemon_name) VALUE ('Pinsir');
INSERT INTO pokemons (pokemon_name) VALUE ('Tauros');
INSERT INTO pokemons (pokemon_name) VALUE ('Magikarp');
INSERT INTO pokemons (pokemon_name) VALUE ('Gyarados');
INSERT INTO pokemons (pokemon_name) VALUE ('Lapras');
INSERT INTO pokemons (pokemon_name) VALUE ('Ditto');
INSERT INTO pokemons (pokemon_name) VALUE ('Eevee');
INSERT INTO pokemons (pokemon_name) VALUE ('Vaporeon');
INSERT INTO pokemons (pokemon_name) VALUE ('Jolteon');
INSERT INTO pokemons (pokemon_name) VALUE ('Flareon');
INSERT INTO pokemons (pokemon_name) VALUE ('Porygon');
INSERT INTO pokemons (pokemon_name) VALUE ('Omanyte');
INSERT INTO pokemons (pokemon_name) VALUE ('Omastar');
INSERT INTO pokemons (pokemon_name) VALUE ('Kabuto');
INSERT INTO pokemons (pokemon_name) VALUE ('Kabutops');
INSERT INTO pokemons (pokemon_name) VALUE ('Aerodactyl');
INSERT INTO pokemons (pokemon_name) VALUE ('Snorlax');
INSERT INTO pokemons (pokemon_name) VALUE ('Articuno');
INSERT INTO pokemons (pokemon_name) VALUE ('Zapdos');
INSERT INTO pokemons (pokemon_name) VALUE ('Moltres');
INSERT INTO pokemons (pokemon_name) VALUE ('Dratini');
INSERT INTO pokemons (pokemon_name) VALUE ('Dragonair');
INSERT INTO pokemons (pokemon_name) VALUE ('Dragonite');
INSERT INTO pokemons (pokemon_name) VALUE ('Mewtwo');
INSERT INTO pokemons (pokemon_name) VALUE ('Mew');

INSERT INTO types (type_name) VALUES ('Grass');
INSERT INTO types (type_name) VALUES ('Poison');
INSERT INTO types (type_name) VALUES ('Fire');
INSERT INTO types (type_name) VALUES ('Flying');
INSERT INTO types (type_name) VALUES ('Water');
INSERT INTO types (type_name) VALUES ('Bug');
INSERT INTO types (type_name) VALUES ('Normal');
INSERT INTO types (type_name) VALUES ('Electric');
INSERT INTO types (type_name) VALUES ('Ground');
INSERT INTO types (type_name) VALUES ('Fairy');
INSERT INTO types (type_name) VALUES ('Fighting');
INSERT INTO types (type_name) VALUES ('Psychic');
INSERT INTO types (type_name) VALUES ('Rock');
INSERT INTO types (type_name) VALUES ('Steel');
INSERT INTO types (type_name) VALUES ('Ice');
INSERT INTO types (type_name) VALUES ('Ghost');
INSERT INTO types (type_name) VALUES ('Dragon');

INSERT INTO pokemons_types VALUES (1,1);
INSERT INTO pokemons_types VALUES (1,2);
INSERT INTO pokemons_types VALUES (2,1);
INSERT INTO pokemons_types VALUES (2,2);
INSERT INTO pokemons_types VALUES (3,1);
INSERT INTO pokemons_types VALUES (3,2);
INSERT INTO pokemons_types VALUES (4,3);
INSERT INTO pokemons_types VALUES (5,3);
INSERT INTO pokemons_types VALUES (6,3);
INSERT INTO pokemons_types VALUES (6,4);
INSERT INTO pokemons_types VALUES (7,5);
INSERT INTO pokemons_types VALUES (8,5);
INSERT INTO pokemons_types VALUES (9,5);
INSERT INTO pokemons_types VALUES (10,6);
INSERT INTO pokemons_types VALUES (11,6);
INSERT INTO pokemons_types VALUES (12,6);
INSERT INTO pokemons_types VALUES (12,4);
INSERT INTO pokemons_types VALUES (13,6);
INSERT INTO pokemons_types VALUES (13,2);
INSERT INTO pokemons_types VALUES (14,6);
INSERT INTO pokemons_types VALUES (14,2);
INSERT INTO pokemons_types VALUES (15,6);
INSERT INTO pokemons_types VALUES (15,2);
INSERT INTO pokemons_types VALUES (16,7);
INSERT INTO pokemons_types VALUES (16,4);
INSERT INTO pokemons_types VALUES (17,7);
INSERT INTO pokemons_types VALUES (17,4);
INSERT INTO pokemons_types VALUES (18,7);
INSERT INTO pokemons_types VALUES (18,4);
INSERT INTO pokemons_types VALUES (19,7);
INSERT INTO pokemons_types VALUES (20,7);
INSERT INTO pokemons_types VALUES (21,7);
INSERT INTO pokemons_types VALUES (21,4);
INSERT INTO pokemons_types VALUES (22,7);
INSERT INTO pokemons_types VALUES (22,4);
INSERT INTO pokemons_types VALUES (23,2);
INSERT INTO pokemons_types VALUES (24,2);
INSERT INTO pokemons_types VALUES (25,8);
INSERT INTO pokemons_types VALUES (26,8);
INSERT INTO pokemons_types VALUES (27,9);
INSERT INTO pokemons_types VALUES (28,9);
INSERT INTO pokemons_types VALUES (29,2);
INSERT INTO pokemons_types VALUES (30,2);
INSERT INTO pokemons_types VALUES (31,2);
INSERT INTO pokemons_types VALUES (31,9);
INSERT INTO pokemons_types VALUES (32,2);
INSERT INTO pokemons_types VALUES (33,2);
INSERT INTO pokemons_types VALUES (34,2);
INSERT INTO pokemons_types VALUES (34,9);
INSERT INTO pokemons_types VALUES (35,10);
INSERT INTO pokemons_types VALUES (36,10);
INSERT INTO pokemons_types VALUES (37,3);
INSERT INTO pokemons_types VALUES (38,3);
INSERT INTO pokemons_types VALUES (39,7);
INSERT INTO pokemons_types VALUES (39,10);
INSERT INTO pokemons_types VALUES (40,7);
INSERT INTO pokemons_types VALUES (40,10);
INSERT INTO pokemons_types VALUES (41,2);
INSERT INTO pokemons_types VALUES (41,4);
INSERT INTO pokemons_types VALUES (42,2);
INSERT INTO pokemons_types VALUES (42,4);
INSERT INTO pokemons_types VALUES (43,1);
INSERT INTO pokemons_types VALUES (43,2);
INSERT INTO pokemons_types VALUES (44,1);
INSERT INTO pokemons_types VALUES (44,2);
INSERT INTO pokemons_types VALUES (45,1);
INSERT INTO pokemons_types VALUES (45,2);
INSERT INTO pokemons_types VALUES (46,6);
INSERT INTO pokemons_types VALUES (46,1);
INSERT INTO pokemons_types VALUES (47,6);
INSERT INTO pokemons_types VALUES (47,1);
INSERT INTO pokemons_types VALUES (48,6);
INSERT INTO pokemons_types VALUES (48,2);
INSERT INTO pokemons_types VALUES (49,6);
INSERT INTO pokemons_types VALUES (49,2);
INSERT INTO pokemons_types VALUES (50,9);
INSERT INTO pokemons_types VALUES (51,9);
INSERT INTO pokemons_types VALUES (52,7);
INSERT INTO pokemons_types VALUES (53,7);
INSERT INTO pokemons_types VALUES (54,5);
INSERT INTO pokemons_types VALUES (55,5);
INSERT INTO pokemons_types VALUES (56,11);
INSERT INTO pokemons_types VALUES (57,11);
INSERT INTO pokemons_types VALUES (58,3);
INSERT INTO pokemons_types VALUES (59,3);
INSERT INTO pokemons_types VALUES (60,5);
INSERT INTO pokemons_types VALUES (61,5);
INSERT INTO pokemons_types VALUES (62,5);
INSERT INTO pokemons_types VALUES (62,11);
INSERT INTO pokemons_types VALUES (63, 12);
INSERT INTO pokemons_types VALUES (64, 12);
INSERT INTO pokemons_types VALUES (65, 12);
INSERT INTO pokemons_types VALUES (66, 11);
INSERT INTO pokemons_types VALUES (67, 11);
INSERT INTO pokemons_types VALUES (68, 11);
INSERT INTO pokemons_types VALUES (69, 1);
INSERT INTO pokemons_types VALUES (69, 2);
INSERT INTO pokemons_types VALUES (70, 1);
INSERT INTO pokemons_types VALUES (70, 2);
INSERT INTO pokemons_types VALUES (71, 1);
INSERT INTO pokemons_types VALUES (71, 2);
INSERT INTO pokemons_types VALUES (72, 5);
INSERT INTO pokemons_types VALUES (72, 2);
INSERT INTO pokemons_types VALUES (73, 5);
INSERT INTO pokemons_types VALUES (73, 2);
INSERT INTO pokemons_types VALUES (74, 13);
INSERT INTO pokemons_types VALUES (74, 9);
INSERT INTO pokemons_types VALUES (75, 13);
INSERT INTO pokemons_types VALUES (75, 9);
INSERT INTO pokemons_types VALUES (76, 13);
INSERT INTO pokemons_types VALUES (76, 9);
INSERT INTO pokemons_types VALUES (77, 3);
INSERT INTO pokemons_types VALUES (78, 3);
INSERT INTO pokemons_types VALUES (79, 5);
INSERT INTO pokemons_types VALUES (79, 12);
INSERT INTO pokemons_types VALUES (80, 5);
INSERT INTO pokemons_types VALUES (80, 12);
INSERT INTO pokemons_types VALUES (81, 8);
INSERT INTO pokemons_types VALUES (81, 14);
INSERT INTO pokemons_types VALUES (82, 8);
INSERT INTO pokemons_types VALUES (82, 14);
INSERT INTO pokemons_types VALUES (83, 7);
INSERT INTO pokemons_types VALUES (83, 4);
INSERT INTO pokemons_types VALUES (84, 7);
INSERT INTO pokemons_types VALUES (84, 4);
INSERT INTO pokemons_types VALUES (85, 7);
INSERT INTO pokemons_types VALUES (85, 4);
INSERT INTO pokemons_types VALUES (86, 5);
INSERT INTO pokemons_types VALUES (87, 5);
INSERT INTO pokemons_types VALUES (87, 15);
INSERT INTO pokemons_types VALUES (88, 2);
INSERT INTO pokemons_types VALUES (89, 2);
INSERT INTO pokemons_types VALUES (90, 5);
INSERT INTO pokemons_types VALUES (91, 5);
INSERT INTO pokemons_types VALUES (91, 15);
INSERT INTO pokemons_types VALUES (92, 16);
INSERT INTO pokemons_types VALUES (92, 2);
INSERT INTO pokemons_types VALUES (93, 16);
INSERT INTO pokemons_types VALUES (93, 2);
INSERT INTO pokemons_types VALUES (94, 16);
INSERT INTO pokemons_types VALUES (94, 2);
INSERT INTO pokemons_types VALUES (95, 13);
INSERT INTO pokemons_types VALUES (95, 9);
INSERT INTO pokemons_types VALUES (96, 12);
INSERT INTO pokemons_types VALUES (97, 12);
INSERT INTO pokemons_types VALUES (98, 5);
INSERT INTO pokemons_types VALUES (99, 5);
INSERT INTO pokemons_types VALUES (100, 8);
INSERT INTO pokemons_types VALUES (101, 8);
INSERT INTO pokemons_types VALUES (102, 1);
INSERT INTO pokemons_types VALUES (102, 12);
INSERT INTO pokemons_types VALUES (103, 1);
INSERT INTO pokemons_types VALUES (103, 12);
INSERT INTO pokemons_types VALUES (104, 9);
INSERT INTO pokemons_types VALUES (105, 9);
INSERT INTO pokemons_types VALUES (106, 11);
INSERT INTO pokemons_types VALUES (107, 11);
INSERT INTO pokemons_types VALUES (108, 7);
INSERT INTO pokemons_types VALUES (109, 2);
INSERT INTO pokemons_types VALUES (110, 2);
INSERT INTO pokemons_types VALUES (111, 9);
INSERT INTO pokemons_types VALUES (111, 13);
INSERT INTO pokemons_types VALUES (112, 9);
INSERT INTO pokemons_types VALUES (112, 13);
INSERT INTO pokemons_types VALUES (113, 7);
INSERT INTO pokemons_types VALUES (114, 1);
INSERT INTO pokemons_types VALUES (115, 7);
INSERT INTO pokemons_types VALUES (116, 5);
INSERT INTO pokemons_types VALUES (117, 5);
INSERT INTO pokemons_types VALUES (118, 5);
INSERT INTO pokemons_types VALUES (119, 5);
INSERT INTO pokemons_types VALUES (120, 5);
INSERT INTO pokemons_types VALUES (121, 5);
INSERT INTO pokemons_types VALUES (121, 12);
INSERT INTO pokemons_types VALUES (122, 12);
INSERT INTO pokemons_types VALUES (122, 10);
INSERT INTO pokemons_types VALUES (123, 6);
INSERT INTO pokemons_types VALUES (123, 11);
INSERT INTO pokemons_types VALUES (124, 15);
INSERT INTO pokemons_types VALUES (124, 12);
INSERT INTO pokemons_types VALUES (125, 8);
INSERT INTO pokemons_types VALUES (126, 3);
INSERT INTO pokemons_types VALUES (127, 6);
INSERT INTO pokemons_types VALUES (128, 7);
INSERT INTO pokemons_types VALUES (129, 5);
INSERT INTO pokemons_types VALUES (130, 5);
INSERT INTO pokemons_types VALUES (130, 4);
INSERT INTO pokemons_types VALUES (131, 5);
INSERT INTO pokemons_types VALUES (131, 15);
INSERT INTO pokemons_types VALUES (132, 7);
INSERT INTO pokemons_types VALUES (133, 7);
INSERT INTO pokemons_types VALUES (134, 5);
INSERT INTO pokemons_types VALUES (135, 8);
INSERT INTO pokemons_types VALUES (136, 3);
INSERT INTO pokemons_types VALUES (137, 7);
INSERT INTO pokemons_types VALUES (138, 13);
INSERT INTO pokemons_types VALUES (138, 5);
INSERT INTO pokemons_types VALUES (139, 13);
INSERT INTO pokemons_types VALUES (139, 5);
INSERT INTO pokemons_types VALUES (140, 13);
INSERT INTO pokemons_types VALUES (140, 5);
INSERT INTO pokemons_types VALUES (141, 13);
INSERT INTO pokemons_types VALUES (141, 5);
INSERT INTO pokemons_types VALUES (142, 13);
INSERT INTO pokemons_types VALUES (142, 4);
INSERT INTO pokemons_types VALUES (143, 7);
INSERT INTO pokemons_types VALUES (144, 15);
INSERT INTO pokemons_types VALUES (144, 4);
INSERT INTO pokemons_types VALUES (145, 8);
INSERT INTO pokemons_types VALUES (145, 4);
INSERT INTO pokemons_types VALUES (146, 3);
INSERT INTO pokemons_types VALUES (146, 4);
INSERT INTO pokemons_types VALUES (147, 17);
INSERT INTO pokemons_types VALUES (148, 17);
INSERT INTO pokemons_types VALUES (149, 17);
INSERT INTO pokemons_types VALUES (149, 4);
INSERT INTO pokemons_types VALUES (150, 12);
INSERT INTO pokemons_types VALUES (151, 12);