INSERT INTO states(is_active) VALUE(1);
INSERT INTO states(is_active) VALUE(0);

INSERT INTO base_stats(hp, attack, defense, speed) VALUES (45, 49, 49, 45);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (60, 62, 63, 60);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (80, 82, 83, 80);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (39, 52, 43, 65);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (58, 64, 58, 80);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (78, 84, 78, 100);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (44, 48, 65, 43);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (59, 63, 80, 58);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (79, 83, 100, 78);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (45, 30, 35, 45);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (50, 20, 55, 30);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (60, 45, 50, 70);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (40, 35, 30, 50);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (45, 25, 50, 35);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (65, 90, 40, 75);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (40, 45, 40, 56);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (63, 60, 55, 71);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (83, 80, 75, 101);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (30, 56, 35, 72);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (55, 81, 60, 97);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (40, 60, 30, 70);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (65, 90, 65, 100);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (35, 60, 44, 55);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (60, 95, 69, 80);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (35, 55, 40, 90);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (60, 90, 55, 110);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (50, 75, 85, 40);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (75, 100, 110, 65);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (55, 47, 52, 41);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (70, 62, 67, 56);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (90, 92, 87, 76);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (46, 57, 40, 50);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (61, 72, 57, 65);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (81, 102, 77, 85);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (70, 45, 48, 35);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (95, 70, 73, 60);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (38, 41, 40, 65);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (73, 76, 75, 100);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (115, 45, 20, 20);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (140, 70, 45, 45);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (40, 45, 35, 55);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (75, 80, 70, 90);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (45, 50, 55, 30);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (60, 65, 70, 40);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (75, 80, 85, 50);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (35, 70, 55, 25);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (60, 95, 80, 30);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (60, 55, 50, 45);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (70, 65, 60, 90);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (10, 55, 25, 95);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (35, 100, 50, 120);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (40, 45, 35, 90);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (65, 70, 60, 115);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (50, 52, 48, 55);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (80, 82, 78, 85);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (40, 80, 35, 70);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (65, 105, 60, 95);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (55, 70, 45, 60);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (90, 110, 80, 95);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (40, 50, 40, 90);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (65, 65, 65, 90);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (90, 95, 95, 70);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (25, 20, 15, 90);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (40, 35, 30, 105);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (55, 50, 45, 120);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (70, 80, 50, 35);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (80, 100, 70, 45);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (90, 130, 80, 55);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (50, 75, 35, 40);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (65, 90, 50, 55);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (80, 105, 65, 70);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (40, 40, 35, 70);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (80, 70, 65, 100);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (40, 80, 100, 20);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (55, 95, 115, 35);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (80, 120, 130, 45);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (50, 85, 55, 90);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (65, 100, 70, 105);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (90, 65, 65, 15);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (95, 75, 110, 30);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (25, 35, 70, 45);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (50, 60, 95, 70);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (52, 90, 55, 60);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (35, 85, 45, 75);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (60, 110, 70, 110);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (65, 45, 55, 45);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (90, 70, 80, 70);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (80, 80, 50, 25);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (105, 105, 75, 50);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (30, 65, 100, 40);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (50, 95, 180, 70);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (30, 35, 30, 80);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (45, 50, 45, 95);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (60, 65, 60, 110);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (35, 45, 160, 70);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (60, 48, 45, 42);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (85, 73, 70, 67);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (30, 105, 90, 50);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (55, 130, 115, 75);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (40, 30, 50, 100);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (60, 50, 70, 150);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (60, 40, 80, 40);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (95, 95, 85, 55);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (50, 50, 95, 35);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (60, 80, 110, 45);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (50, 120, 53, 87);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (50, 105, 79, 76);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (90, 55, 75, 30);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (40, 65, 95, 35);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (65, 90, 120, 60);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (80, 85, 95, 25);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (105, 130, 120, 40);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (250, 5, 5, 50);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (65, 55, 115, 60);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (105, 95, 80, 90);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (30, 40, 70, 60);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (55, 65, 95, 85);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (45, 67, 60, 63);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (80, 92, 65, 68);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (30, 45, 55, 85);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (60, 75, 85, 115);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (40, 45, 65, 90);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (70, 110, 80, 105);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (65, 50, 35, 95);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (65, 83, 57, 105);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (65, 95, 57, 93);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (65, 125, 100, 85);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (75, 100, 95, 110);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (20, 10, 55, 80);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (95, 125, 79, 81);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (130, 85, 80, 60);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (48, 48, 48, 48);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (55, 55, 50, 55);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (130, 65, 60, 65);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (65, 65, 60, 130);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (65, 130, 60, 65);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (65, 60, 70, 40);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (35, 40, 100, 35);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (70, 60, 125, 55);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (30, 80, 90, 55);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (60, 115, 105, 80);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (80, 105, 65, 130);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (160, 110, 65, 30);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (90, 85, 100, 85);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (90, 90, 85, 100);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (90, 100, 90, 90);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (41, 64, 45, 50);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (61, 84, 65, 70);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (91, 134, 95, 80);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (106, 110, 90, 130);
INSERT INTO base_stats(hp, attack, defense, speed) VALUES (110, 110, 110, 110);

INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Bulbasaur', 1, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Ivysaur', 2, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Venusaur', 3, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Charmander', 4, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Charmeleon', 5, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Charizard', 6, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Squirtle', 7, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Wartortle', 8, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Blastoise', 9, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Caterpie', 10, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Metapod', 11, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Butterfree', 12, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Weedle', 13, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Kakuna', 14, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Beedrill', 15, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Pidgey', 16, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Pidgeotto', 17, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Pidgeot', 18, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Rattata', 19, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Raticate', 20, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Spearow', 21, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Fearow', 22, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Ekans', 23, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Arbok', 24, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Pikachu', 25, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Raichu', 26, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Sandshrew', 27, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Sandslash', 28, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Nidoran-W', 29, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Nidorina', 30, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Nidoqueen', 31, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Nidoran-M', 32, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Nidorino', 33, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Nidoking', 34, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Clefairy', 35, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Clefable', 36, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Vulpix', 37, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Ninetales', 38, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Jigglypuff', 39, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Wigglytuff', 40, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Zubat', 41, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Golbat', 42, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Oddish', 43, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Gloom', 44, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Vileplume', 45, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Paras', 46, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Parasect', 47, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Venonat', 48, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Venomoth', 49, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Diglett', 50, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Dugtrio', 51, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Meowth', 52, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Persian', 53, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Psyduck', 54, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Golduck', 55, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Mankey', 56, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Primeape', 57, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Growlithe', 58, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Arcanine', 59, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Poliwag', 60, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Poliwhirl', 61, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Poliwrath', 62, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Abra', 63, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Kadabra', 64, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Alakazam', 65, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Machop', 66, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Machoke', 67, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Machamp', 68, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Bellsprout', 69, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Weepinbell', 70, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Victreebel', 71, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Tentacool', 72, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Tentacruel', 73, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Geodude', 74, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Graveler', 75, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Golem', 76, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Ponyta', 77, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Rapidash', 78, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Slowpoke', 79, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Slowbro', 80, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Magnemite', 81, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Magneton', 82, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Farfetchd', 83, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Doduo', 84, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Dodrio', 85, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Seel', 86, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Dewgong', 87, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Grimer', 88, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Muk', 89, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Shellder', 90, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Cloyster', 91, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Gastly', 92, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Haunter', 93, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Gengar', 94, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Onix', 95, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Drowzee', 96, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Hypno', 97, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Krabby', 98, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Kingler', 99, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Voltorb', 100, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Electrode', 101, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Exeggcute', 102, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Exeggutor', 103, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Cubone', 104, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Marowak', 105, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Hitmonlee', 106, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Hitmonchan', 107, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Lickitung', 108, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Koffing', 109, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Weezing', 110, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Rhyhorn', 111, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Rhydon', 112, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Chansey', 113, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Tangela', 114, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Kangaskhan', 115, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Horsea', 116, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Seadra', 117, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Goldeen', 118, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Seaking', 119, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Staryu', 120, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Starmie', 121, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Mr. Mime', 122, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Scyther', 123, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Jynx', 124, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Electabuzz', 125, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Magmar', 126, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Pinsir', 127, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Tauros', 128, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Magikarp', 129, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Gyarados', 130, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Lapras', 131, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Ditto', 132, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Eevee', 133, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Vaporeon', 134, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Jolteon', 135, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Flareon', 136, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Porygon', 137, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Omanyte', 138, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Omastar', 139, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Kabuto', 140, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Kabutops', 141, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Aerodactyl', 142, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Snorlax', 143, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Articuno', 144, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Zapdos', 145, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Moltres', 146, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Dratini', 147, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Dragonair', 148, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Dragonite', 149, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Mewtwo', 150, 1);
INSERT INTO pokemons (pokemon_name, base_stats_id, state_id) VALUES ('Mew', 151, 1);

INSERT INTO types (type_name, state_id) VALUES ('Grass', 1);
INSERT INTO types (type_name, state_id) VALUES ('Poison', 1);
INSERT INTO types (type_name, state_id) VALUES ('Fire', 1);
INSERT INTO types (type_name, state_id) VALUES ('Flying', 1);
INSERT INTO types (type_name, state_id) VALUES ('Water', 1);
INSERT INTO types (type_name, state_id) VALUES ('Bug', 1);
INSERT INTO types (type_name, state_id) VALUES ('Normal', 1);
INSERT INTO types (type_name, state_id) VALUES ('Electric', 1);
INSERT INTO types (type_name, state_id) VALUES ('Ground', 1);
INSERT INTO types (type_name, state_id) VALUES ('Fairy', 1);
INSERT INTO types (type_name, state_id) VALUES ('Fighting', 1);
INSERT INTO types (type_name, state_id) VALUES ('Psychic', 1);
INSERT INTO types (type_name, state_id) VALUES ('Rock', 1);
INSERT INTO types (type_name, state_id) VALUES ('Steel', 1);
INSERT INTO types (type_name, state_id) VALUES ('Ice', 1);
INSERT INTO types (type_name, state_id) VALUES ('Ghost', 1);
INSERT INTO types (type_name, state_id) VALUES ('Dragon', 1);

INSERT INTO pokemons_types VALUES (1,1);
INSERT INTO pokemons_types VALUES (1,2);
INSERT INTO pokemons_types VALUES (2,1);
INSERT INTO pokemons_types VALUES (2,2);
INSERT INTO pokemons_types VALUES (3,1);
INSERT INTO pokemons_types VALUES (3,2);
INSERT INTO pokemons_types VALUES (4,3);
INSERT INTO pokemons_types VALUES (5,3);
INSERT INTO pokemons_types VALUES (6,3);
INSERT INTO pokemons_types VALUES (6,4);
INSERT INTO pokemons_types VALUES (7,5);
INSERT INTO pokemons_types VALUES (8,5);
INSERT INTO pokemons_types VALUES (9,5);
INSERT INTO pokemons_types VALUES (10,6);
INSERT INTO pokemons_types VALUES (11,6);
INSERT INTO pokemons_types VALUES (12,6);
INSERT INTO pokemons_types VALUES (12,4);
INSERT INTO pokemons_types VALUES (13,6);
INSERT INTO pokemons_types VALUES (13,2);
INSERT INTO pokemons_types VALUES (14,6);
INSERT INTO pokemons_types VALUES (14,2);
INSERT INTO pokemons_types VALUES (15,6);
INSERT INTO pokemons_types VALUES (15,2);
INSERT INTO pokemons_types VALUES (16,7);
INSERT INTO pokemons_types VALUES (16,4);
INSERT INTO pokemons_types VALUES (17,7);
INSERT INTO pokemons_types VALUES (17,4);
INSERT INTO pokemons_types VALUES (18,7);
INSERT INTO pokemons_types VALUES (18,4);
INSERT INTO pokemons_types VALUES (19,7);
INSERT INTO pokemons_types VALUES (20,7);
INSERT INTO pokemons_types VALUES (21,7);
INSERT INTO pokemons_types VALUES (21,4);
INSERT INTO pokemons_types VALUES (22,7);
INSERT INTO pokemons_types VALUES (22,4);
INSERT INTO pokemons_types VALUES (23,2);
INSERT INTO pokemons_types VALUES (24,2);
INSERT INTO pokemons_types VALUES (25,8);
INSERT INTO pokemons_types VALUES (26,8);
INSERT INTO pokemons_types VALUES (27,9);
INSERT INTO pokemons_types VALUES (28,9);
INSERT INTO pokemons_types VALUES (29,2);
INSERT INTO pokemons_types VALUES (30,2);
INSERT INTO pokemons_types VALUES (31,2);
INSERT INTO pokemons_types VALUES (31,9);
INSERT INTO pokemons_types VALUES (32,2);
INSERT INTO pokemons_types VALUES (33,2);
INSERT INTO pokemons_types VALUES (34,2);
INSERT INTO pokemons_types VALUES (34,9);
INSERT INTO pokemons_types VALUES (35,10);
INSERT INTO pokemons_types VALUES (36,10);
INSERT INTO pokemons_types VALUES (37,3);
INSERT INTO pokemons_types VALUES (38,3);
INSERT INTO pokemons_types VALUES (39,7);
INSERT INTO pokemons_types VALUES (39,10);
INSERT INTO pokemons_types VALUES (40,7);
INSERT INTO pokemons_types VALUES (40,10);
INSERT INTO pokemons_types VALUES (41,2);
INSERT INTO pokemons_types VALUES (41,4);
INSERT INTO pokemons_types VALUES (42,2);
INSERT INTO pokemons_types VALUES (42,4);
INSERT INTO pokemons_types VALUES (43,1);
INSERT INTO pokemons_types VALUES (43,2);
INSERT INTO pokemons_types VALUES (44,1);
INSERT INTO pokemons_types VALUES (44,2);
INSERT INTO pokemons_types VALUES (45,1);
INSERT INTO pokemons_types VALUES (45,2);
INSERT INTO pokemons_types VALUES (46,6);
INSERT INTO pokemons_types VALUES (46,1);
INSERT INTO pokemons_types VALUES (47,6);
INSERT INTO pokemons_types VALUES (47,1);
INSERT INTO pokemons_types VALUES (48,6);
INSERT INTO pokemons_types VALUES (48,2);
INSERT INTO pokemons_types VALUES (49,6);
INSERT INTO pokemons_types VALUES (49,2);
INSERT INTO pokemons_types VALUES (50,9);
INSERT INTO pokemons_types VALUES (51,9);
INSERT INTO pokemons_types VALUES (52,7);
INSERT INTO pokemons_types VALUES (53,7);
INSERT INTO pokemons_types VALUES (54,5);
INSERT INTO pokemons_types VALUES (55,5);
INSERT INTO pokemons_types VALUES (56,11);
INSERT INTO pokemons_types VALUES (57,11);
INSERT INTO pokemons_types VALUES (58,3);
INSERT INTO pokemons_types VALUES (59,3);
INSERT INTO pokemons_types VALUES (60,5);
INSERT INTO pokemons_types VALUES (61,5);
INSERT INTO pokemons_types VALUES (62,5);
INSERT INTO pokemons_types VALUES (62,11);
INSERT INTO pokemons_types VALUES (63, 12);
INSERT INTO pokemons_types VALUES (64, 12);
INSERT INTO pokemons_types VALUES (65, 12);
INSERT INTO pokemons_types VALUES (66, 11);
INSERT INTO pokemons_types VALUES (67, 11);
INSERT INTO pokemons_types VALUES (68, 11);
INSERT INTO pokemons_types VALUES (69, 1);
INSERT INTO pokemons_types VALUES (69, 2);
INSERT INTO pokemons_types VALUES (70, 1);
INSERT INTO pokemons_types VALUES (70, 2);
INSERT INTO pokemons_types VALUES (71, 1);
INSERT INTO pokemons_types VALUES (71, 2);
INSERT INTO pokemons_types VALUES (72, 5);
INSERT INTO pokemons_types VALUES (72, 2);
INSERT INTO pokemons_types VALUES (73, 5);
INSERT INTO pokemons_types VALUES (73, 2);
INSERT INTO pokemons_types VALUES (74, 13);
INSERT INTO pokemons_types VALUES (74, 9);
INSERT INTO pokemons_types VALUES (75, 13);
INSERT INTO pokemons_types VALUES (75, 9);
INSERT INTO pokemons_types VALUES (76, 13);
INSERT INTO pokemons_types VALUES (76, 9);
INSERT INTO pokemons_types VALUES (77, 3);
INSERT INTO pokemons_types VALUES (78, 3);
INSERT INTO pokemons_types VALUES (79, 5);
INSERT INTO pokemons_types VALUES (79, 12);
INSERT INTO pokemons_types VALUES (80, 5);
INSERT INTO pokemons_types VALUES (80, 12);
INSERT INTO pokemons_types VALUES (81, 8);
INSERT INTO pokemons_types VALUES (81, 14);
INSERT INTO pokemons_types VALUES (82, 8);
INSERT INTO pokemons_types VALUES (82, 14);
INSERT INTO pokemons_types VALUES (83, 7);
INSERT INTO pokemons_types VALUES (83, 4);
INSERT INTO pokemons_types VALUES (84, 7);
INSERT INTO pokemons_types VALUES (84, 4);
INSERT INTO pokemons_types VALUES (85, 7);
INSERT INTO pokemons_types VALUES (85, 4);
INSERT INTO pokemons_types VALUES (86, 5);
INSERT INTO pokemons_types VALUES (87, 5);
INSERT INTO pokemons_types VALUES (87, 15);
INSERT INTO pokemons_types VALUES (88, 2);
INSERT INTO pokemons_types VALUES (89, 2);
INSERT INTO pokemons_types VALUES (90, 5);
INSERT INTO pokemons_types VALUES (91, 5);
INSERT INTO pokemons_types VALUES (91, 15);
INSERT INTO pokemons_types VALUES (92, 16);
INSERT INTO pokemons_types VALUES (92, 2);
INSERT INTO pokemons_types VALUES (93, 16);
INSERT INTO pokemons_types VALUES (93, 2);
INSERT INTO pokemons_types VALUES (94, 16);
INSERT INTO pokemons_types VALUES (94, 2);
INSERT INTO pokemons_types VALUES (95, 13);
INSERT INTO pokemons_types VALUES (95, 9);
INSERT INTO pokemons_types VALUES (96, 12);
INSERT INTO pokemons_types VALUES (97, 12);
INSERT INTO pokemons_types VALUES (98, 5);
INSERT INTO pokemons_types VALUES (99, 5);
INSERT INTO pokemons_types VALUES (100, 8);
INSERT INTO pokemons_types VALUES (101, 8);
INSERT INTO pokemons_types VALUES (102, 1);
INSERT INTO pokemons_types VALUES (102, 12);
INSERT INTO pokemons_types VALUES (103, 1);
INSERT INTO pokemons_types VALUES (103, 12);
INSERT INTO pokemons_types VALUES (104, 9);
INSERT INTO pokemons_types VALUES (105, 9);
INSERT INTO pokemons_types VALUES (106, 11);
INSERT INTO pokemons_types VALUES (107, 11);
INSERT INTO pokemons_types VALUES (108, 7);
INSERT INTO pokemons_types VALUES (109, 2);
INSERT INTO pokemons_types VALUES (110, 2);
INSERT INTO pokemons_types VALUES (111, 9);
INSERT INTO pokemons_types VALUES (111, 13);
INSERT INTO pokemons_types VALUES (112, 9);
INSERT INTO pokemons_types VALUES (112, 13);
INSERT INTO pokemons_types VALUES (113, 7);
INSERT INTO pokemons_types VALUES (114, 1);
INSERT INTO pokemons_types VALUES (115, 7);
INSERT INTO pokemons_types VALUES (116, 5);
INSERT INTO pokemons_types VALUES (117, 5);
INSERT INTO pokemons_types VALUES (118, 5);
INSERT INTO pokemons_types VALUES (119, 5);
INSERT INTO pokemons_types VALUES (120, 5);
INSERT INTO pokemons_types VALUES (121, 5);
INSERT INTO pokemons_types VALUES (121, 12);
INSERT INTO pokemons_types VALUES (122, 12);
INSERT INTO pokemons_types VALUES (122, 10);
INSERT INTO pokemons_types VALUES (123, 6);
INSERT INTO pokemons_types VALUES (123, 11);
INSERT INTO pokemons_types VALUES (124, 15);
INSERT INTO pokemons_types VALUES (124, 12);
INSERT INTO pokemons_types VALUES (125, 8);
INSERT INTO pokemons_types VALUES (126, 3);
INSERT INTO pokemons_types VALUES (127, 6);
INSERT INTO pokemons_types VALUES (128, 7);
INSERT INTO pokemons_types VALUES (129, 5);
INSERT INTO pokemons_types VALUES (130, 5);
INSERT INTO pokemons_types VALUES (130, 4);
INSERT INTO pokemons_types VALUES (131, 5);
INSERT INTO pokemons_types VALUES (131, 15);
INSERT INTO pokemons_types VALUES (132, 7);
INSERT INTO pokemons_types VALUES (133, 7);
INSERT INTO pokemons_types VALUES (134, 5);
INSERT INTO pokemons_types VALUES (135, 8);
INSERT INTO pokemons_types VALUES (136, 3);
INSERT INTO pokemons_types VALUES (137, 7);
INSERT INTO pokemons_types VALUES (138, 13);
INSERT INTO pokemons_types VALUES (138, 5);
INSERT INTO pokemons_types VALUES (139, 13);
INSERT INTO pokemons_types VALUES (139, 5);
INSERT INTO pokemons_types VALUES (140, 13);
INSERT INTO pokemons_types VALUES (140, 5);
INSERT INTO pokemons_types VALUES (141, 13);
INSERT INTO pokemons_types VALUES (141, 5);
INSERT INTO pokemons_types VALUES (142, 13);
INSERT INTO pokemons_types VALUES (142, 4);
INSERT INTO pokemons_types VALUES (143, 7);
INSERT INTO pokemons_types VALUES (144, 15);
INSERT INTO pokemons_types VALUES (144, 4);
INSERT INTO pokemons_types VALUES (145, 8);
INSERT INTO pokemons_types VALUES (145, 4);
INSERT INTO pokemons_types VALUES (146, 3);
INSERT INTO pokemons_types VALUES (146, 4);
INSERT INTO pokemons_types VALUES (147, 17);
INSERT INTO pokemons_types VALUES (148, 17);
INSERT INTO pokemons_types VALUES (149, 17);
INSERT INTO pokemons_types VALUES (149, 4);
INSERT INTO pokemons_types VALUES (150, 12);
INSERT INTO pokemons_types VALUES (151, 12);